Repository modern-agile-team/7term-mini-back, pull requests merged in 2024-02, with the labels that each got.

#10 Setting/#9: setup project
  README.md
  app/src/config/db.js
Labels: db, setting

#12 setting/#11: express-validator
  app/package-lock.json
  app/package.json
Labels: setting

#15 Feature/#7 로그인 기능 및 토큰 발행, 검증 구현
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/config/test.js
  app/src/models/auth/authRepository.js
  app/src/models/auth/authService.js
  app/src/models/auth/jwtService.js
  app/src/models/test.js
  app/src/routes/auth/authCtrl.js
  app/src/routes/auth/authMiddleware.js
  app/src/routes/auth/authRoutes.js
  app/src/routes/test.js
Labels: feature

#19 feature/#6: 게시판 CRUD 구현
  app/app.js
  app/src/models/board/boardRepository.js
  app/src/models/board/boardService.js
  app/src/routes/board/boardCtrl.js
  app/src/routes/board/boardRoutes.js
  app/src/routes/board/boardValidation.js
Labels: feature

#18 feature/#13: 메인페이지 구현
  app/app.js
  app/src/models/mainpage/mainpageRepository.js
  app/src/models/mainpage/mainpageService.js
  app/src/routes/mainpage/mainpageCtrl.js
  app/src/routes/mainpage/mainpageRoutes.js
  app/src/routes/mainpage/mainpageValidation.js
Labels: feature

#21 Feature/#14: 게시글 댓글 구현
  app/app.js
  app/src/models/auth/jwtService.js
  app/src/models/comment/commentService.js
  app/src/models/comment/commnetRepository.js
  app/src/routes/auth/authRoutes.js
  app/src/routes/comment/commentCtrl.js
  app/src/routes/comment/commentRouters.js
  app/src/routes/comment/commentValidation.js
Labels: feature

#22 Feature/#5: 게시글 좋아요 기능 구현
  app/app.js
  app/package-lock.json
  app/src/models/love/loveRepository.js
  app/src/models/love/loveService.js
  app/src/routes/auth/authCtrl.js
  app/src/routes/auth/authMiddleware.js
  app/src/routes/love/loveCtrl.js
  app/src/routes/love/loveRouters.js
  app/src/routes/love/loveValidation.js
Labels: feature

#20 Refactor#17: 로그인 API 리팩토링
  app/app.js
  app/src/models/auth/authRepository.js
  app/src/models/auth/authService.js
  app/src/models/auth/jwtService.js
  app/src/routes/auth/authCtrl.js
  app/src/routes/auth/authMiddleware.js
  app/src/routes/auth/authRoutes.js
Labels: refactor

#23 Feature/#4 회원가입 구현
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/models/user/userRepository.js
  app/src/models/user/userService.js
  app/src/routes/user/userCtrl.js
  app/src/routes/user/userRoutes.js
  app/src/routes/user/userValidation.js
Labels: feature

#25 bugfix/#24: 서버를 위해 USER를 user로 변경함
  app/src/models/mainpage/mainpageRepository.js
Labels: bugfix

#27 Refactor/#14: 댓글 API 경로 수정 및 중복제거
  app/app.js
  app/package-lock.json
  app/src/models/auth/jwtService.js
  app/src/models/comment/commentService.js
  app/src/models/comment/commnetRepository.js
  app/src/routes/comment/commentCtrl.js
  app/src/routes/comment/commentRouters.js
  app/src/routes/comment/commentValidation.js
Labels: refactor

#28 Feature/#4: 회원 탈퇴 기능 추가 및 로그인 로직 수정
  app/app.js
  app/package-lock.json
  app/src/models/auth/authRepository.js
  app/src/models/auth/authService.js
  app/src/models/user/userRepository.js
  app/src/models/user/userService.js
  app/src/routes/user/userCtrl.js
  app/src/routes/user/userRoutes.js
Labels: feature, modify

#30 refactor/#26: 보드 라우터, 각 repository 수정 및 기타 코드 리팩토링
  app/app.js
  app/src/models/auth/authRepository.js
  app/src/models/auth/authService.js
  app/src/models/auth/jwtService.js
  app/src/models/board/boardRepository.js
  app/src/models/board/boardService.js
  app/src/models/comment/commentService.js
  app/src/models/comment/commnetRepository.js
  app/src/models/love/loveRepository.js
  app/src/models/love/loveService.js
  app/src/models/mainpage/mainpageRepository.js
  app/src/models/mainpage/mainpageService.js
  app/src/models/user/userRepository.js
  app/src/routes/board/boardCtrl.js
  app/src/routes/board/boardRoutes.js
  app/src/routes/board/boardValidation.js
  app/src/routes/board/comment/commentCtrl.js
  app/src/routes/board/comment/commentValidation.js
  app/src/routes/board/love/loveCtrl.js
  app/src/routes/board/love/loveValidation.js
  app/src/routes/comment/commentRouters.js
  app/src/routes/love/loveRouters.js
  app/src/routes/mainpage/mainpageCtrl.js
  app/src/routes/mainpage/mainpageRoutes.js
  app/src/routes/mainpage/mainpageValidation.js
  app/src/routes/user/userValidation.js
Labels: refactor

#31 Feature/#7: 로그아웃 기능 구현
  app/src/models/auth/authRepository.js
  app/src/models/auth/authService.js
  app/src/routes/auth/authCtrl.js
  app/src/routes/auth/authMiddleware.js
  app/src/routes/auth/authRoutes.js
  app/src/routes/user/userRoutes.js
Labels: feature, refactor

#34 Refactor/board board 오타수정 및 return문 추가
  app/src/models/board/boardRepository.js
  app/src/models/board/boardService.js
  app/src/routes/board/boardCtrl.js
Labels: refactor

#35 Feature/user 로그인 공백 검사 validation 추가
  app/src/models/auth/authService.js
  app/src/models/user/userService.js
  app/src/routes/auth/authRoutes.js
  app/src/routes/auth/authValidation.js
Labels: refactor

#36 Feature/#29: 마이페이지 구현
  app/package-lock.json
  app/src/models/auth/authService.js
  app/src/models/user/userService.js
  app/src/routes/auth/authRoutes.js
  app/src/routes/user/userCtrl.js
  app/src/routes/user/userRoutes.js
Labels: feature

#39 Modify/#37: 시간 수정을 위한 db.js 수정
  app/src/config/db.js
Labels: modify

#42 Feature/board 인기 카테고리로 인한 변화
  app/src/models/board/boardRepository.js
  app/src/models/board/boardService.js
Labels: feature, db, modify

#43 Modify/#5: 좋아요 생성 시 게시글 고유번호 자연수 확인 과정 추가 및 카멜 케이스 적용
  app/src/models/love/loveService.js
  app/src/routes/board/boardRoutes.js
  app/src/routes/board/love/loveValidation.js
Labels: refactor, modify

#40 feature/#7: 로그아웃시 액세스 토큰도 같이 사용 불가 로직 추가
  app/src/models/auth/authRepository.js
  app/src/models/auth/authService.js
  app/src/routes/auth/authCtrl.js
  app/src/routes/auth/authMiddleware.js
Labels: feature, db, modify
